baseURL: "https://mdinata.my.id"
languageCode: "en-US"
title: "Hendra Manudinata"
theme: ["PaperMod"]
params:
  profileMode:
    enabled: true
    title: "Hendra Manudinata"
    subtitle: "Just an ordinary 'hooman'"
    imageUrl: "https://avatars.githubusercontent.com/u/116422610"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: "WordPress"
        url: "https://manoedinata.wordpress.com"
      - name: "Medium"
        url: "https://medium.com/@manoedinata"
  socialIcons:
    - name: "GitHub"
      url: "https://github.com/manoedinata"
    - name: "Instagram"
      url: "https://instagram.com/manoedinata"
    - name: "Telegram"
      url: "https://t.me/manoedinata"
    - name: "Email"
      url: "mailto:manoedinata@gmail.com"
